# Generated by Django 3.1.1 on 2020-09-23 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('dateRegistered', models.DateField(default=datetime.datetime.now)),
                ('SKU', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('genericName', models.CharField(max_length=100)),
                ('commonBrand', models.CharField(max_length=100)),
                ('manufacturedDate', models.DateField(default=datetime.datetime.now)),
                ('expiryDate', models.DateField(default=datetime.datetime.now)),
                ('size', models.IntegerField()),
                ('howToUse', models.TextField()),
                ('sideEffects', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('noOfItems', models.IntegerField()),
                ('images', models.ImageField(upload_to='upload/')),
            ],
            options={
                'db_table': 'Medicine',
            },
        ),
    ]
